### PR TITLE
18Scan improvements

### PR DESCRIPTION
**Pull request by timbovelander**
There was a minor bug in the 18Scan game data, the starting location for minor company 1 was missing from the map.
I also made a lot of improvements, fixed some minor bugs and added some small features. The commit messages describe what changed.

### CODE REVIEW

**Comment by kelsin** [comment]
This looks great. 

One requested change: Can you move the "sc" tiles into the game definition file? You can remove the "sc" from the id, and instead of just the quantity you can put the tile definition object right there in the file. In that way 18Scan will redefine those tiles JUST for that game. Much cleaner!

It was a recently added feature.

**Comment by kelsin** [comment]
Note: if you need a quantity > 1, you can add a `quantity` field to the definition in the game file.

**Comment by timbovelander** [comment]
> This looks great.
> 
> One requested change: Can you move the "sc" tiles into the game definition file? You can remove the "sc" from the id, and instead of just the quantity you can put the tile definition object right there in the file. In that way 18Scan will redefine those tiles JUST for that game. Much cleaner!
> 
> It was a recently added feature.

Oh, that is much better! Thanks, I changed it as requested.

**Comment by kelsin** [comment]
Excellent! Just so you know for the future,  if you ever have a game that just has a otherwise-known tile but names it differently you can do that too: `"57": {"tile": 58, "quantity": 2}`. For example, that puts two tile 58's in the game, but labels them as 57 (again, just for that game).

Rock on!

**Pull request merged**
