### PR TITLE
Fix distance between pins and tiles (die)

### PR DESCRIPTION
**Pull request by Galatolol**
Issue #85

### CODE REVIEW

**Comment by kelsin** [comment]
I'm super confused only cause I've printed out test sheets before and they work on the die, so this being wrong just feels weird to me despite all of the math working on with how you have it. I'm definitely including the bleed in the distance between the pin and the blade despite theoretically not needing it. Just measured the die as well and it's definitely .375" from the center of the pin to the blade.

I will print out test pages with master and this branch tomorrow to test. Sorry for the delay.

I think we can also do this just be changing `c.bleedHeight` to `c.height` here: https://github.com/kelsin/18xx/blob/master/src/tilesheet/util.js#L46

Will test that out if needed and might close this and implement that way since it's logical about how the layout is happening instead of adding to `extraY`.

**Comment by kelsin** [comment]
I did not get to this at work this week and I apologize. It was busy and I blatantly forgot. I will try to attend to this as soon as I can access a printer for testing (probably Monday).

**Comment by Paperemail** [comment]
On the same request, you could also fix for the die cut only would be to add the blank hex space in columns instead of rows. Right now it uses up to 4 blank hexes to change between the colors if it were the other way it would use only one blank hex.
[1830 TilesDie.pdf](https://github.com/kelsin/18xx/files/3389521/1830.TilesDie.pdf)

**Comment by kelsin** [comment]
Opened #88 for that request @Paperemail definitely a good one!

**Comment by Paperemail** [comment]
I found out why the die works for your die and not the others.  For die CST13296 the pin is 2.8mm looks like the die you use the pin is 5mm.

**Comment by Paperemail** [comment]
Common dies used for 18xx
1837637_Hexes_CST13296_Final
1837637_Sm_Rectangles_CST13774_Final
1837637_Rectangles_Final
1837637_Hexes_CST13296_2_Final

**Comment by kelsin** [comment]
Printed these out, will test tomorrow morning (not getting home until late tonight) and will finally close this out tomorrow.

**Comment by kelsin** [comment]
Sorry this took so long, but my test prints from before must have been on older code that didn't include this bug, it was clearly wrong now. Fixed!

**Pull request closed without merging**
