### PR TITLE
Adding support for the small die, closes #116

### LINKED ISSUE #116: support for small die-cut tiles
There is a standard for the small 1822-sized tiles for a die cutter.  It would be nice to have the tile generator able to generate that size and layout of tiles.  I've attached the die cutter overlay for that size.

[small hex overlay.pdf](https://github.com/kelsin/18xx/files/3847315/small.hex.overlay.pdf)

### PR DESCRIPTION
**Pull request by kelsin**

### CODE REVIEW

**Comment by knauman** [comment]
The printout trims off the left and right edges. Possibly the margins on the paper are too large? 
small_die_edge_trimmed

**Comment by kelsin** [comment]
This should be outside of the bleed and not affect what you cut. Since the
due is about exactly 8 inches wide it will go past safe margins on most
printers. Just need someone with the die to test and make sure it’s only
bleed hanging off.

**Comment by knauman** [comment]
I don’t have my dies yet so I can not test.

**Comment by Paperemail** [comment]
If you email me the PDF files I can test it.

**Comment by knauman** [comment]
I sent it to you on the 18xx slack.

**Comment by kelsin** [comment]
@Paperemail

[1830-small-tiles.pdf](https://github.com/kelsin/18xx/files/4013186/1830-small-tiles.pdf)
[1849-small-tiles.pdf](https://github.com/kelsin/18xx/files/4013187/1849-small-tiles.pdf)
[1860-small-tiles.pdf](https://github.com/kelsin/18xx/files/4013188/1860-small-tiles.pdf)

**Comment by Paperemail** [comment]
Trested tiles today  the bleed works well. The edges  are within 2mm of the edges that are missing so it works. You may want to add 1830 page 1of2 and 1830 2of2 to the pages.

On Dec 31, 2019, at 11:25 AM, Christopher Giroir <notifications@github.com<mailto:notifications@github.com>> wrote:


@Paperemail<https://github.com/Paperemail>

1830-small-tiles.pdf<https://github.com/kelsin/18xx/files/4013186/1830-small-tiles.pdf>
1849-small-tiles.pdf<https://github.com/kelsin/18xx/files/4013187/1849-small-tiles.pdf>
1860-small-tiles.pdf<https://github.com/kelsin/18xx/files/4013188/1860-small-tiles.pdf>

**Pull request merged**
