### PR TITLE
EU logos

### PR DESCRIPTION
**Pull request by Galatolol**
I want you to see this logo before I do the rest. I removed everything that wasn't indispensable, but the SVG file is still much bigger than others.

### CODE REVIEW

**Comment by kelsin** [comment]
I added this one manually. I now have a plugin involved (no docs yet) that will do ALL of the svg work I need. All you should have to do (after making the SVG in whatever program you like) is drop it in the logos folder and run `yarn svgo` from the root folder of the project. It will output how much it minimized the SVG for you at that point. I will be running that as part of merging PR's as well. This logo (minimized) is now added to master!

**Comment by kelsin** [comment]
Actually that NFL svg really had issue so I removed it again, will add it again in a sec. Looks like it uses xlink in some required say which doesn't play nice with svgo or react. Looking into it.

**Comment by kelsin** [comment]
Found it, just needed to remove the `xlink:href` and change them to `href`, all done.

More info: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

**Comment by Galatolol** [comment]
I did Belge logo (scale to width of 2in, replace `xlink:href` by `href` and run yarn `svgo`). This step of replacing xlink crashes the logo. I'll try to find a solution.

I think that linking logos to abbreviations is a dead end (risk of conflicts). Wouldn't it be possible to have an attribute "logo" in company's definition?

**Comment by kelsin** [comment]
For now we'll keep doing abbrev's but probably will change it soon where you tell it what SVG to use in the company definition section of the game, and we can name the svg's however we want (still something clean for my OCD)

**Pull request closed without merging**
