### PR TITLE
Allows for setting map styles based on game data

### PR DESCRIPTION
**Pull request by gragatrim**
With this you can set the background styles(and any other styles)
in the game data file. This allows for an image to be set for the
background, then you can set the transparency(using 0-1) and it
will set the opacity at that level so you can see the background
image.

### CODE REVIEW

**Comment by gragatrim** [comment]
This doesn't work for the paginated map page.... I haven't worked much on that bit of the code so I'm not sure how it decides how to split things up.

**Comment by kelsin** [comment]
Ahhh makes sense, I can take a look. It mainly just uses the same SVG data with different viewports. Would mean positioning the background image at the right offsets for each tile. I can take a shot at it later today I bet (or later this week due to the holiday).

**Comment by kelsin** [comment]
Just as a note, I still like this idea but will probably take what you've done and try to incorporate it after a rework on the color system that I'm working on now. Soon!

**Comment by kelsin** [comment]
This PR got old enough that it's out of data. I don't mind merging if if you want to resubmit against latest code. Sorry for the delay on that :-(

**Pull request closed without merging**
